import streamlit as st
import pandas as pd

st.set_page_config(layout="wide", page_title="Market Leaders")

st.title("💎 Institutional Watchlist")
st.write("This list is automatically updated daily at Market Close via GitHub Actions.")

try:
    # Read the file generated by the background scan
    df = pd.read_csv("daily_watchlist.csv")
    
    if not df.empty:
        st.success(f"Found {len(df)} stocks meeting the $300M Cap & 2.0x RVOL criteria.")
        
        # Display as a clean table
        st.dataframe(
            df.sort_values(by="Max_RVOL", ascending=False),
            use_container_width=True,
            column_config={
                "Max_RVOL": st.column_config.NumberColumn("Volume Surge (x)", format="%.2f"),
                "Market_Cap_M": st.column_config.NumberColumn("Cap ($M)", format="$%d")
            }
        )
    else:
        st.warning("Scan completed, but no stocks met the criteria today.")
        
except FileNotFoundError:
    st.error("No data found. Please run the GitHub Action manually for the first time.")

st.divider()
st.caption("Scan Logic: 6-Month Breakout + 10-Day Relative Volume Surge > 2.0x")
