import streamlit as st
import pandas as pd
import yfinance as yf
import os
import datetime
import time

# --- CONFIGURATION ---
st.set_page_config(layout="wide", page_title="180-Day Momentum Scanner")

st.title("🏹 Momentum Strategy Command Center")
st.subheader("180-Day Range Breakouts & Industry Analysis")

# --- FUNCTIONS ---

@st.cache_data(ttl=86400)
def get_industry_safe(ticker):
    """Fetches industry metadata with 24-hour caching to stay fast."""
    try:
        time.sleep(0.1)  # Small delay to prevent yfinance rate limits
        tk = yf.Ticker(ticker)
        # Returns industry or a placeholder if not found
        return tk.info.get('industry', 'Unknown 🔍')
    except:
        return "N/A"

def convert_df(df):
    """Prepares the dataframe for the download button."""
    return df.to_csv(index=False).encode('utf-8')

# --- MAIN LOGIC ---

# Check for the file generated by your 6 AM IST GitHub Action
if os.path.exists("daily_watchlist.csv"):
    df = pd.read_csv("daily_watchlist.csv")
    
    if not df.empty:
        # 1. Momentum Calculations
        # We ensure Annualized Return (Velocity) is calculated if not already in CSV
        if 'Slope' in df.columns and 'Price' in df.columns:
            df['Velocity %'] = (df['Slope'] / df['Price']) * 252 * 100
        
        # 2. Add TradingView Link Column
        df['Chart 📈'] = df['Ticker'].apply(lambda x: f"https://www.tradingview.com/symbols/{x}/")
        
        # 3. Sidebar Filters
        st.sidebar.header("🎯 Quality Filters")
        min_rvol = st.sidebar.slider("Min Relative Volume (RVOL)", 0.0, 10.0, 1.2, help="Institutions buy on high volume")
        min_velocity = st.sidebar.slider("Min Velocity %", 0, 500, 30, help="Annualized speed of the breakout")
        
        # Industry Toggle (Fetching industry can be slow for 100+ stocks, so we make it optional)
        load_industry = st.sidebar.checkbox("🔍 Load Industry Data", value=True)
        
        # Apply Technical Filters
        df_filtered = df[(df['RVOL'] >= min_rvol) & (df['Velocity %'] >= min_velocity)].copy()
        df_filtered = df_filtered.sort_values(by="Velocity %", ascending=False)

        # 4. Fetch Industry Data if enabled
        if load_industry:
            with st.spinner("Classifying Sectors..."):
                df_filtered['Industry'] = df_filtered['Ticker'].apply(get_industry_safe)
        else:
            df_filtered['Industry'] = "Click sidebar to load"

        # 5. Export Button
        csv_data = convert_df(df_filtered)
        st.sidebar.download_button(
            label="📥 Download This List",
            data=csv_data,
            file_name=f"Breakouts_{datetime.date.today()}.csv",
            mime="text/csv",
        )

        # 6. Main Table Display
        st.markdown(f"Displaying **{len(df_filtered)}** stocks matching your criteria.")
        
        st.dataframe(
            df_filtered,
            use_container_width=True,
            column_config={
                "Ticker": st.column_config.TextColumn("Ticker", width="small"),
                "Industry": st.column_config.TextColumn("Industry", width="medium"),
                "Chart 📈": st.column_config.LinkColumn("Chart", display_text="View"),
                "Price": st.column_config.NumberColumn("Price", format="$%.2f"),
                "Velocity %": st.column_config.NumberColumn("Velocity %", format="%.0f%%"),
                "RVOL": st.column_config.NumberColumn("Rel Vol", format="%.2fx"),
                "High_180d": None, 
                "Slope": None 
            },
            hide_index=True
        )

    else:
        st.warning("No stocks found in the CSV. Try adjusting your scanner.py parameters.")
else:
    st.error("Missing 'daily_watchlist.csv'. Please check if your 6:00 AM IST GitHub Action completed successfully.")
